version: '3.8'

services:
  backend:
    build: ./packages/backend
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_ROOT_PASSWORD}

volumes:
  mongo-data:
