version: '3.8'

services:
  backend:
    build: ./packages/backend
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_ROOT_PASSWORD}

  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - minio-data:/mnt/data
    ports:
      - '9000:9000'
      - '9090:9090'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9090" /minio1/mnt/data

volumes:
  mongo-data:
  minio-data:
